name: flutter_fab_dialer
description: A new flutter package project.
version: 0.1.0
author: Leondev7 <leondev7jgt@gmail.com>
homepage: https://github.com/Leondev7/flutter_fab_dialer

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  test: ^1.3.3

environment:
  sdk: ">=2.1.0-dev.3.1 <3.0.0"